### ISSUE TITLE
[frontend] 매뉴얼 페이지 UI

### ISSUE THREAD

**Issue by kan9suyeon** [smu-commuting/smu-commuting#32]
- [x] 매뉴얼 페이지 헤더 UI개발
- [x] 버스정보
- [x] 택시합승
- [x] 커뮤니티
- [x] 닫기 버튼

**Comment by colo1211** [comment]
수연아 개발 완료하고 PR 완료한 이슈들은 Close issue 눌러줘!

**Comment by kan9suyeon** [comment]
> 수연아 개발 완료하고 PR 완료한 이슈들은 Close issue 눌러줘!

넵
